spring:
  application:
    name: user-service
  datasource:
    url: ${PG_URL:jdbc:postgresql://postgres:5432/aihr}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          url: ${PG_URL:jdbc:postgresql://postgres:5432/aihr}
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: users
    baseline-on-migrate: true
    validate-on-migrate: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
