server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/aihr}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:lBfTfVC8zzwmUV5XLIJzuJj0VOZhTVTj6F5kx3QnzGmvz1hpkBHj7ptj6FBwGNH6}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 3600000
  refresh-expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
