spring:
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/aihr}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.vladnekrasov: INFO
