name: Deploy User Service

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Build with Gradle
      working-directory: ./user-service
      run: ./gradlew build -x test
    
    - name: Build Docker image
      working-directory: ./user-service
      run: docker build -t user-service:latest .
    
    - name: Save Docker image
      run: docker save user-service:latest | gzip > user-service.tar.gz
    
    - name: Copy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_KEY }}
        source: "user-service.tar.gz"
        target: "/tmp"
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /tmp
          docker load < user-service.tar.gz
          docker stop user-service || true
          docker rm user-service || true
          docker run -d --name user-service --network host \
            -e PG_URL=${{ secrets.PG_URL }} \
            -e PG_USERNAME=${{ secrets.PG_USERNAME }} \
            -e PG_PASSWORD=${{ secrets.PG_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --restart unless-stopped \
            user-service:latest
          rm user-service.tar.gz
